# Generated by Django 4.0.3 on 2022-03-27 15:50

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Video Title')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Video Description')),
                ('cover_image', models.ImageField(null=True, upload_to='video/cover_image/')),
                ('video', models.FileField(upload_to='videos/')),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=6)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Publishing Date')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channel.channel')),
                ('likes', models.ManyToManyField(blank=True, related_name='video_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'ordering': ['-publishing_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='channel.channel', verbose_name='Channel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='video.comment')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='video.video')),
            ],
        ),
    ]
